-- Fix barangay_zone_settings id to auto-increment instead of default 1.

alter table public.barangay_zone_settings
  alter column id drop default;

alter table public.barangay_zone_settings
  alter column id add generated by default as identity;
